import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from '@clerk/themes';
import { Toaster } from "react-hot-toast";
import Header from "./dashboard/_components/Header";
import NextTopLoader from "nextjs-toploader";
import LayoutWrapper from "./_components/LayoutWrapper";

const clerkPublishableKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY;


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }} publishableKey={clerkPublishableKey}>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <NextTopLoader />
          <Toaster position="bottom-center" />
          <LayoutWrapper children={children} />
          {/* <div className="mx-5 md:mx-20 lg:mx-36">
            {children}
          </div> */}
        </body>
      </html>
    </ClerkProvider>

  );
}
